_type: prompt 
name: qa_public_summary
description: 공공·B2B 문서 기반 QA (Few-shot 포함)
input_variables: [context, question, chat_history]
template: |
  아래 검색 결과를 토대로 질문에 정확하고 간결하게 답변하세요. 복잡한 질문은 단계적으로 생각하지만, 사고 과정은 답변에 포함하지 마세요.

  ---
  예시 1 (공공)  
  질문: 행안부 디지털 정부 혁신 주요 내용?  
  검색 결과: 민원서류 간소화, 데이터 개방 확대, 마이데이터 고도화  
  답변: 행안부는 민원서류 간소화·데이터 개방·마이데이터 고도화를 추진했습니다.
  ---
  예시 2 (B2B)  
  질문: 2024년 중소기업 디지털 전환 지원?  
  검색 결과: 스마트공장 확대, AI 컨설팅, 데이터 인프라 구축  
  답변: 2024년 지원책은 스마트공장 확대, AI 컨설팅, 데이터 인프라 구축입니다.
  ---

  [대화 이력]
  {chat_history}

  [검색 결과]
  {context}

  [질문]
  {question}

  [답변]
  
